### ISSUE TITLE
Creating new wallets doesn't work on most devices for v5 wownerujo branch

### ISSUE THREAD

**Issue by fuwa0529** [fuwa0529/wownerujo#12]
A common pattern for devices that do not work is that they run lineageos.

The screen will get stuck in the creating wallet page forever after clicking the create button, there's no error in the log and no crash ...

**Comment by wowario** [comment]
Old bulletproof support and difficulty fix not yet applied to v0.5 branch

**Comment by fuwa0529** [comment]
Getting some mixed results here, azy on irc reported that it worked on a "samsung galaxy s3, latest lineage os".

**Comment by fuwa0529** [comment]
This has been fixed (somehow) on the latest build 2c44fb79. The initial sync can take quite some time though.
