### ISSUE TITLE
Incompatible with the popular Android devices

### ISSUE THREAD

**Issue by HiFromAjay** [fuwa0529/wownerujo#13]
The app is incompatible with the popular Android devices currently in use such as Galaxy Grand Prime, J2, J1 Ace, and Oppo A37f. The devices support min SDK 22. However, the app supports min SDK 23. Therefore, the app is not available in the Play store on the aforementioned devices.

**Comment by fuwa0529** [comment]
Yeah, the support was dropped on purpose:

https://github.com/fuwa0529/wownerujo/blob/b447fa5a24c4021615de01d25a2595aa74c92934/app/build.gradle#L9

**Comment by fuwa0529** [comment]
I'm closing this now, thx for the report.
