### ISSUE TITLE
references to monerujo.io

### ISSUE THREAD

**Issue by m2049r** [fuwa0529/wownerujo#5]
Although it's really cool that this is based on monerujo - I can't give support for wownerujo - and I am getting support requests for WOW.

Please remove references to monerujo.io.

**Comment by fuwa0529** [comment]
That was not the intention, but sure, will do.

**Comment by fuwa0529** [comment]
@m2049r I've removed the references to monerujo.io in the Readme.md, do you want it to be removed in the credit page as well?

**Comment by m2049r** [comment]
good question - maybe "forked from monerujo.io (no support there)"?

**Comment by fuwa0529** [comment]
We certainly don't want people to misunderstood where the support should happen, I'll add that (no support there) phase in the credit page, is that OK?

**Comment by fuwa0529** [comment]
@m2049r how about this?

https://github.com/fuwa0529/wownerujo/commit/56d161d01bf3624641425283f37781d25d5b50a9

**Comment by m2049r** [comment]
Cool :)
